spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: postgres

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true


 freemarker:
   expose-request-attributes: true







springdoc:
  api-docs:
    path: "/api-docs"

logging:
  level:
    ru.quizapp: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    max-history: 7
    max-size: 10MB