spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: postgres

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

springdoc:
  api-docs:
    path: "/v3/api-docs"
  swagger-ui:
    disable-swagger-default-url: true
    groups-order: DESC
    operationsSorter: method
    use-root-path: true
    display-query-params-without-oauth2: true
    url: "/v3/api-docs"
  show-actuator: true
management:
  endpoint:
    health:
      show-details: when_authorized

logging:
  level:
    ru.quizapp: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  file:
    max-history: 7
    max-size: 10MB


